(function(){
 'use strict';
 const style=document.createElement('style');
 style.textContent=`
 html,body{height:100%;overflow:hidden;font-size:15px} #app{display:flex;flex-direction:column;height:100dvh}
 header{flex:none;display:flex;flex-wrap:wrap;padding:10px 12px;gap:8px;height:auto}header .hosp{display:none}header .logo{font-size:19px}
 header>a,#editBtn,#editBar{display:none!important}#darkBtn{margin-left:auto}.gsearch{order:3;width:100%;flex-basis:100%}.gsearch{position:relative}.gsearch input{padding-right:48px!important;font-size:16px;min-height:44px;border-radius:10px}
 .mobile-search-clear{position:absolute;right:8px;top:2px;min-width:40px;min-height:40px;border:0;background:transparent;color:var(--mut);font-size:25px;z-index:3}.mobile-search-clear[hidden]{display:none}.mobile-all-title{font-size:17px;padding:12px;margin:0} .gs-drop{top:48px;max-height:calc(100dvh - 210px);border-radius:12px}.gs-item{padding:16px 12px}.gs-desc{font-size:16px!important;line-height:1.45}.gs-meta{margin-top:8px}
 .sidebar{display:none}main{min-height:0;flex:1;overflow:auto;padding-bottom:60px}main>div{flex:none!important;overflow:visible!important}.card-list{overflow:visible!important;padding:12px!important;display:block!important}.multi-wrap{padding:12px!important}
 .proc-card{width:100%;max-width:none;min-height:66px;padding:16px 12px;gap:10px;border-radius:12px;background:var(--sur)}.pc-desc{font-size:16px!important;line-height:1.45}.pc-aa{display:none}.pc-chevron{flex:none}
 .mobile-specialty{order:4;width:100%;min-height:44px;font:inherit;color:var(--txt);background:var(--sur);border:1px solid var(--brd);border-radius:10px;padding:8px}
 .mobile-nav{position:fixed;bottom:0;left:0;right:0;height:56px;display:flex;background:var(--sur);border-top:1px solid var(--brd);z-index:150;padding-bottom:env(safe-area-inset-bottom)}.mobile-nav a{flex:1;display:flex;align-items:center;justify-content:center;color:var(--acc);text-decoration:none;font-size:13px}
 .card-detail.mobile-full{position:fixed!important;inset:0!important;width:100%!important;height:100dvh!important;max-width:none!important;margin:0!important;overflow:auto!important;background:var(--sur);z-index:1000;border:0;border-radius:0;padding-bottom:30px;box-sizing:border-box}.mobile-detail-head{position:sticky;top:0;background:var(--sur);border-bottom:1px solid var(--brd);padding:12px;z-index:2}.mobile-detail-head button{font:inherit;background:none;border:0;color:var(--acc);min-height:44px}.mobile-detail-head h2{font-size:19px;line-height:1.5;margin:8px 0}.mobile-detail-head small{color:var(--mut)}
 .mobile-full .detail-wrap{padding:12px!important;max-width:100%;display:block!important}.mobile-full table{width:100%!important;min-width:0!important;table-layout:fixed}.mobile-full td,.mobile-full th{overflow-wrap:anywhere;white-space:normal!important;padding:10px 6px!important}.mobile-full .dt-label{width:43%!important}.mobile-full .dt-val{width:57%!important}.mobile-full .card-detail-close{display:none}.drawer{inset:0;width:100%;max-width:100%;height:100dvh;border-radius:0;z-index:1000}.instr-body{overflow-wrap:anywhere}
 `;
 document.head.append(style);
 const header=document.querySelector('#app>header');
 if(!header)return;
 const select=document.createElement('select');select.className='mobile-specialty';select.setAttribute('aria-label','Επιλογή ειδικότητας');header.append(select);
 let optionsSignature='',allSelected=false;
 const main=document.querySelector('main');const allList=document.createElement('div');allList.id='mobileAll';allList.style.display='none';main.append(allList);
 function chooseSpecialty(value){allSelected=value==='all';allList.style.display=allSelected?'block':'none';if(!allSelected){document.querySelectorAll('.sb-item')[Number(value)]?.click();return;}allList.replaceChildren();[...document.querySelectorAll('.sb-item')].forEach((item,i)=>{if(item.classList.contains('locked'))return;item.click();const source=[...main.querySelectorAll('[id^="view"]')].find(v=>v.style.display!=='none'&&v.querySelector('.proc-card'));if(!source)return;const heading=document.createElement('h2');heading.className='mobile-all-title';heading.textContent=item.querySelector('span')?.textContent||'';allList.append(heading);[...source.querySelectorAll('.proc-card')].forEach((card,index)=>{const button=document.createElement('button');button.className='proc-card';button.style.textAlign='left';const label=document.createElement('span');label.className='pc-desc';label.textContent=card.querySelector('.pc-desc')?.textContent||card.textContent;button.append(label);button.onclick=()=>{item.click();const target=[...document.getElementById(source.id).querySelectorAll('.proc-card')][index];target?.click();};allList.append(button);});});main.querySelectorAll('[id^="view"]').forEach(v=>v.style.display='none');select.value='all';}
 const searchInput=document.getElementById('gsInput');const clear=document.createElement('button');clear.type='button';clear.className='mobile-search-clear';clear.textContent='×';clear.setAttribute('aria-label','Καθαρισμός αναζήτησης πράξεων');clear.hidden=!searchInput.value;searchInput.parentElement.append(clear);searchInput.addEventListener('input',()=>{clear.hidden=!searchInput.value;});clear.onclick=()=>{searchInput.value='';globalSearch('');clear.hidden=true;searchInput.focus();};
 function syncSpecialties(){const items=[...document.querySelectorAll('.sb-item')];const sig=items.map(x=>x.textContent).join('|');if(sig!==optionsSignature){optionsSignature=sig;select.replaceChildren();const allOption=document.createElement('option');allOption.value='all';allOption.textContent='Όλες οι ειδικότητες';select.append(allOption);items.forEach((item,i)=>{const o=document.createElement('option');o.value=i;o.textContent=item.querySelector("span")?.textContent+" · "+(item.querySelector(".sb-count")?.textContent||"");o.disabled=item.classList.contains('locked');select.append(o);});}const active=items.findIndex(x=>x.classList.contains('active'));if(allSelected)select.value='all';else if(active>=0)select.value=active;}
 select.onchange=()=>{chooseSpecialty(select.value);main.scrollTop=0;};
 const nav=document.createElement('nav');nav.className='mobile-nav';nav.setAttribute('aria-label','Πλοήγηση');[['Κατάλογος','index.html'],['Plafond','plafond.html'],['Κατηγορίες','katigoriopoiisi.html']].forEach(([label,path])=>{const a=document.createElement('a');a.textContent=label;a.href='https://mediterraneohospital.github.io/mediprice/mobile/'+path;nav.append(a);});document.body.append(nav);
 const baseSearch=window.globalSearch;
 if(baseSearch)window.globalSearch=function(q){baseSearch(q);const needle=norm(q);if(!needle)return;const drop=document.getElementById('gsDrop');GNATHO.sections.forEach((section,si)=>section.subtables.forEach((table,sti)=>{if(table.kind!=='procedures')return;table.rows.forEach((row,ri)=>{if(!norm(row.desc).includes(needle))return;drop.querySelector('.gs-empty')?.remove();const item=document.createElement('div');item.className='gs-item';const title=document.createElement('div');title.className='gs-desc';title.textContent=row.desc;const meta=document.createElement('div');meta.className='gs-meta';meta.textContent='Γναθοχειρουργικά';item.append(title,meta);item.onclick=()=>{drop.classList.remove('open');document.getElementById('gsInput').value='';showView('gnatho');const cards=[...document.querySelectorAll('#viewGnatho .proc-card')];const target=cards.find(c=>(c.getAttribute('onclick')||'').includes('toggleGnathoProcCard('+si+','+sti+','+ri+','));if(target)toggleGnathoProcCard(si,sti,ri,target);};drop.append(item);});}));};
 let current=null,card=null,snapshot=null,previousFocus=null;
 function remember(){snapshot={q:document.getElementById('gsInput')?.value||'',results:document.getElementById('gsDrop')?.innerHTML||'',searchOpen:document.getElementById('gsDrop')?.classList.contains('open'),specialty:select.value,scroll:document.querySelector('main').scrollTop};}
 document.addEventListener('click',e=>{if(e.target.closest('.proc-card,.gs-item'))remember();},true);
 function restore(){if(current){current.remove();current=null;}card?.classList.remove('active');if(snapshot){const input=document.getElementById('gsInput'),drop=document.getElementById('gsDrop');chooseSpecialty(snapshot.specialty);input.value=snapshot.q;clear.hidden=!input.value;globalSearch(snapshot.q);drop.classList.toggle('open',!!snapshot.searchOpen);document.querySelector('main').scrollTop=snapshot.scroll;}previousFocus?.focus({preventScroll:true});}
 window.addEventListener('message',e=>{if(e.source===parent&&e.data?.type==='mp-mobile-back')restore();});
 const observer=new MutationObserver(()=>{syncSpecialties();const detail=document.querySelector('.card-detail:not(.mobile-full)');if(!detail||current)return;card=detail.previousElementSibling;current=detail;previousFocus=document.activeElement;detail.classList.add('mobile-full');detail.setAttribute('role','dialog');detail.setAttribute('aria-modal','true');const title=card?.querySelector('.pc-desc')?.textContent||card?.textContent||'Λεπτομέρειες πράξης';const head=document.createElement('div');head.className='mobile-detail-head';const back=document.createElement('button');back.textContent='‹ Πίσω';back.onclick=()=>parent.postMessage({type:'mp-mobile-close'},parent.location.origin);const category=document.createElement('small');category.textContent=select.selectedOptions[0]?.textContent||'';const h=document.createElement('h2');h.textContent=title;head.append(back,category,h);detail.prepend(head);detail.scrollTop=0;back.focus();parent.postMessage({type:'mp-mobile-open'},parent.location.origin);});observer.observe(document.querySelector('main'),{childList:true,subtree:true});observer.observe(document.getElementById('sbList'),{childList:true,subtree:true});syncSpecialties();
})();



